name = "loki-log-shipper"
type = "webpack"
account_id = "***REMOVED***"
workers_dev = true
route = ""
zone_id = "***REMOVED***"
webpack_config = "webpack.config.js"

[env.dev]
webpack_config = "webpack.dev.config.js"
