name = "loki-log-shipper"
type = "webpack"
workers_dev = true
route = ""
webpack_config = "webpack.config.js"
vars = { OPTIONS = '{"css":false,"images":false,"js":false,"ip":false}', LOKI_HOST="loki.jorgelbg.me", CLIENT_ID="asd", IPINFO_TOKEN="asd" }

[env.dev]
webpack_config = "webpack.dev.config.js"
